ShopBanHang/Areas/Admin/Controllers/OrderController.cs
using PagedList;
using ShopBanHang.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopBanHang.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        // GET: Admin/Order
        ShopBanQuanAoEntities dbObj = new ShopBanQuanAoEntities();

        public ActionResult Index(string currentFilter, string Search, int? page)
        {

            var users = new List<Order>();
            if (Search != null)
                page = 1;
            else
            {
                Search = currentFilter;
            }
            if (!string.IsNullOrEmpty(Search))
                // chúng ta gọi lấy thông tin theo tin khóa name
                users = dbObj.Orders.Where(n => n.Name.Contains(Search)).ToList();
            else
            {
                users = dbObj.Orders.ToList();// hiểu thị toàn bộ thông tin sản phẩm
            }
            ViewBag.CurrentFilter = Search;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            //  Sắp xếp theo id sản phẩm, sp mới đưa lên đầu
            users = users.OrderByDescending(n => n.Id).ToList();
            return View(users.ToPagedList(pageNumber, pageSize));

        }
        public ActionResult Details(int id)
        {
            var DetailsUsers = dbObj.Orders.Where(n => n.Id == id).FirstOrDefault();
            return View(DetailsUsers);
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/User/Create
        [HttpPost]
        public ActionResult Create(Order order)
        {
            dbObj.Orders.Add(order);

            dbObj.SaveChanges();

            return RedirectToAction("Index");
        }
        // GET: Admin/User/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var objOrder = dbObj.Orders.Where(n => n.Id == id).FirstOrDefault();
            return View(objOrder);
        }

        // POST: Admin/User/Edit/5
        [HttpPost]
        public ActionResult Edit(Order order)
        {
            dbObj.Entry(order).State = EntityState.Modified;
            dbObj.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var objUser = dbObj.Orders.Where(n => n.Id == id).FirstOrDefault();
            return View(objUser);
        }
        // POST: Admin/User/Delete/5
        [HttpPost]

        public ActionResult Delete(Order order)
        {
            var objUser = dbObj.Orders.Where(n => n.Id == order.Id).FirstOrDefault();
            dbObj.Orders.Remove(objUser);
            dbObj.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ShopBanHang/Areas/Admin/Controllers/UserController.cs
using PagedList;
using ShopBanHang.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ShopBanHang.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        // GET: Admin/User
        ShopBanQuanAoEntities dbObj = new ShopBanQuanAoEntities();
        
        public ActionResult Index(string currentFilter, string Search, int? page)
        {
            
            var users = new List<User>();
            if (Search != null)
                page = 1;
            else
            {
                Search = currentFilter;
            }
            if (!string.IsNullOrEmpty(Search))
                // chúng ta gọi lấy thông tin theo tin khóa name
                users = dbObj.Users.Where(n => n.Email.Contains(Search)).ToList();
            else
            {
                users = dbObj.Users.ToList();// hiểu thị toàn bộ thông tin sản phẩm
            }
            ViewBag.CurrentFilter = Search;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
           //  Sắp xếp theo id sản phẩm, sp mới đưa lên đầu
            users = users.OrderByDescending(n => n.Id).ToList();
            return View(users.ToPagedList(pageNumber, pageSize));
            
        }

        // GET: Admin/User/Details/5
        public ActionResult Details(int id)
        {
            var DetailsUsers = dbObj.Users.Where(n => n.Id == id).FirstOrDefault();
            return View(DetailsUsers);
        }

        // GET: Admin/User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/User/Create
        [HttpPost]
        public ActionResult Create(User user)
        {
                    dbObj.Users.Add(user);

                    dbObj.SaveChanges();

                    return RedirectToAction("Index");
                }
            // GET: Admin/User/Edit/5
            [HttpGet]
        public ActionResult Edit(int id)
        {
            var objUser = dbObj.Users.Where(n => n.Id == id).FirstOrDefault();
            return View(objUser);
        }

        // POST: Admin/User/Edit/5
        [HttpPost]
        public ActionResult Edit(User user)
        {
            dbObj.Entry(user).State = EntityState.Modified;
            dbObj.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Admin/User/Delete/5
        public ActionResult Delete(int id)
        {
            var objUser = dbObj.Users.Where(n => n.Id == id).FirstOrDefault();
            return View(objUser);
        }
        // POST: Admin/User/Delete/5
        [HttpPost]
     
        public ActionResult Delete(User user)
        {
            var objUser = dbObj.Users.Where(n => n.Id == user.Id).FirstOrDefault();
            dbObj.Users.Remove(objUser);
            dbObj.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ShopBanHang/Areas/Admin/Views/Order/Create.cshtml
@model ShopBanHang.Context.Order

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div style="margin-left: 100px;">
    <h2>Tạo mới</h2>

    @using (Html.BeginForm("Create", "Order", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Order</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedOnUtc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

ShopBanHang/Areas/Admin/Views/Order/Delete.cshtml
@model ShopBanHang.Context.Order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div style="margin-left: 100px;">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>User</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedOnUtc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedOnUtc)
            </dd>

        </dl>

        @using (Html.BeginForm("Delete", "Order", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </div>

ShopBanHang/Areas/Admin/Views/Order/Details.cshtml
@model ShopBanHang.Context.Order

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div style="margin-left: 100px">
    <h2>Chi tiết đặt hàng</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOnUtc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShopBanHang/Areas/Admin/Views/Order/Edit.cshtml
@model ShopBanHang.Context.Order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div style="margin-left: 100px;">
<h2>Sửa</h2>

@using (Html.BeginForm("Edit", "Order", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOnUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
    </div>

ShopBanHang/Areas/Admin/Views/Order/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<ShopBanHang.Context.Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .pagination {
        display: inline-block;
        padding-left: 0;
        margin: 20px 0;
        border-radius: 4px;
    }

        .pagination > li {
            display: inherit;
        }

            .pagination > li > a,
            .pagination > li > span {
                position: relative;
                float: left;
                padding: 6px 12px;
                margin-left: -1px;
                line-height: 1.5;
                text-decoration: none;
                background-color: #ffffff;
                border: 1px solid #dddddd;
            }

            .pagination > li:first-child > a,
            .pagination > li:first-child > span {
                margin-left: 0;
                border-bottom-left-radius: 4px;
                border-top-left-radius: 4px;
            }

            .pagination > li:last-child > a,
            .pagination > li:last-child > span {
                border-top-left-radius: 4px;
                border-bottom-left-radius: 4px;
            }

            .pagination > li > a:hover,
            .pagination > li > span:hover,
            .pagination > li > a:focus,
            .pagination > li > span:focus {
                background-color: #eeeeee,
            }

        .pagination > .active > a,
        .pagination > .active > span,
        .pagination > a.active > a:hover,
        .pagination > a.active > span:hover,
        .pagination > a.active > a:focus,
        .pagination > a.active > span:focus {
            z-index: 2;
            color: #ffffff;
            cursor: default;
            background-color: #428bca;
            border-color: #428bca;
        }

        .pagination > .disabled > span,
        .pagination > .disabled > a,
        .pagination > .disabled > a:hover,
        .pagination > .disabled > a:focus {
            color: #999999;
            cursor: not-allowed;
            background-color: #ffffff;
            border-color: #dddddd;
        }

    .pagination-lg > li > a,
    .pagination-lg > li > span {
        padding: 10px 16px;
        font-size: 18px;
    }
</style>
<style>
    .pagination {
        display: inline-block;
        padding-left: 0;
        margin: 20px 0;
        border-radius: 4px;
    }

        .pagination > li {
            display: inherit;
        }

            .pagination > li > a,
            .pagination > li > span {
                position: relative;
                float: left;
                padding: 6px 12px;
                margin-left: -1px;
                line-height: 1.5;
                text-decoration: none;
                background-color: #ffffff;
                border: 1px solid #dddddd;
            }

            .pagination > li:first-child > a,
            .pagination > li:first-child > span {
                margin-left: 0;
                border-bottom-left-radius: 4px;
                border-top-left-radius: 4px;
            }

            .pagination > li:last-child > a,
            .pagination > li:last-child > span {
                border-top-left-radius: 4px;
                border-bottom-left-radius: 4px;
            }

            .pagination > li > a:hover,
            .pagination > li > span:hover,
            .pagination > li > a:focus,
            .pagination > li > span:focus {
                background-color: #eeeeee,
            }

        .pagination > .active > a,
        .pagination > .active > span,
        .pagination > a.active > a:hover,
        .pagination > a.active > span:hover,
        .pagination > a.active > a:focus,
        .pagination > a.active > span:focus {
            z-index: 2;
            color: #ffffff;
            cursor: default;
            background-color: #428bca;
            border-color: #428bca;
        }

        .pagination > .disabled > span,
        .pagination > .disabled > a,
        .pagination > .disabled > a:hover,
        .pagination > .disabled > a:focus {
            color: #999999;
            cursor: not-allowed;
            background-color: #ffffff;
            border-color: #dddddd;
        }

    .pagination-lg > li > a,
    .pagination-lg > li > span {
        padding: 10px 16px;
        font-size: 18px;
    }
</style>
<div style="margin-left: 100px">
    <h2>Quản lý Đặt hàng</h2>

    <p>
        <a href="@Url.Action("Create")" class="btn btn-default"><i class="fa fa-plus"></i>Tạo mới</a>

    </p>
    @using (Html.BeginForm("Index", "User", FormMethod.Get, new { enctype = "multipart/form-data" }))
    {
<p>
    Tìm tên sản phẩm: @Html.TextBox("Search", ViewBag.CurrentFilter as string)
    <input type="submit" value="Tìm kiếm" />
</p>}
    <table class="table table-striped">
        <thead class="table-bordered" style="background-color:darkcyan">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().UserId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().CreatedOnUtc)
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedOnUtc)
    </td>
    <td>
        <a href="@Url.Action("Edit",new { id = item.Id })" class="btn btn-success"><i class="fa fa-pencil-alt"></i> Edit </a>
        <a href="@Url.Action("Details",new { id = item.Id })" class="btn btn-dark"><i class="fa fa-info"></i> Detail </a>
        <a href="@Url.Action("Delete",new { id = item.Id })" class="btn btn-danger"><i class="fa fa-trash"></i> Delete </a>
    </td>
</tr>
}

    </table>
    Trang@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.currentFilter }))
</div>