ShopBanHang/Controllers/CartController.cs
using PayPal.Api;
using ShopBanHang.Context;
using ShopBanHang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopBanHang.Controllers
{
    public class CartController : Controller
    {
        ShopBanQuanAoEntities dbObj = new ShopBanQuanAoEntities();

        // GET: Cart
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { product = dbObj.Products.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
                
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { product = dbObj.Products.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                   
                }
                Session["cart"] = cart;
                

            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].product.Id.Equals(id))
                    return i;
            return -1;
        }
       
        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.product.Id == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
      
        public ActionResult PaymentWithPaypal(string Cancel)
        {
            //getting the apiContext  
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal  
                //Payer Id will be returned when payment proceeds or click to pay  
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist  
                    //it is returned by the create function call of the payment class  
                    // Creating a payment  
                    // baseURL is the url on which paypal sendsback the data.  
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/Cart/Home?";
                    //here we are generating guid for storing the paymentID received in session  
                    //which will be used in the payment execution  
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url  
                    //on which payer is redirected for paypal account payment  
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    //get links returned from paypal in response to Create function call  
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment  
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    // saving the paymentID in the key guid  
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment  
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user  
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }
                }
            }
            catch (Exception)
            {
                return View("FailureView");
            }
            //on successful payment, show success page to user.  
            return View("SuccessView");
        }
        private PayPal.Api.Payment payment;
        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };
            this.payment = new Payment()
            {
                id = paymentId
            };
            return this.payment.Execute(apiContext, paymentExecution);
        }
        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
              
            var itemList = new ItemList()
            {
                items = new List<Item>()
            };

            List<CartModel> cart = new List<CartModel>();
            //var lstCart = (List<CartModel>)Session["cart"];
            var total = cart.Sum(p => p.product.Price);
            
            //Adding Item Details like name, currency, price etc  
            foreach (var item in cart)
            {
                itemList.items.Add(new Item()
                {
                    name = item.product.Name,
                    currency = "USD",
                    price = (item.product.Price/23300).ToString(),
                    quantity =item.Quantity.ToString(),
                    sku = "sku"
                });
            }
            
            var payer = new Payer()
            {
                payment_method = "paypal"
            };
            // Configure Redirect Urls here with RedirectUrls object  
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };
            // Adding Tax, shipping and Subtotal details  
            var details = new Details()
            {
                tax = "0",
                shipping = "0",
                subtotal ="1244.63" //total.ToString()
            };
            //Final amount with details  
            var amount = new Amount()
            {
                currency = "USD",
                total = "1244.63", // Total must be equal to sum of tax, shipping and subtotal.  
                details = details
            };
            var paypalOrderId = DateTime.Now.Ticks;
            var transactionList = new List<Transaction>();

            // Adding description about the transaction  
            transactionList.Add(new Transaction()
            {
                description = $"Invoice #{paypalOrderId}",
                invoice_number = paypalOrderId.ToString(), //Generate an Invoice No  
                amount =  amount,
                item_list = itemList
            });
            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };
            // Create a payment using a APIContext  
            return this.payment.Create(apiContext);
        }
        public ActionResult Home()
        {
            return View();
        }
    }
}

ShopBanHang/Controllers/CategoryController.cs
using ShopBanHang.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopBanHang.Controllers
{
    public class CategoryController : Controller
    {
        ShopBanQuanAoEntities shopBanHangEntities = new ShopBanQuanAoEntities();
        // GET: Category
        public ActionResult Index()
        {
            var lstCategory = shopBanHangEntities.Categories.ToList();
                return View(lstCategory);
        }
        public ActionResult ProductCategory(int Id)
        {
            var lstProduct = shopBanHangEntities.Products.Where(n => n.CategoryId == Id).ToList();
            return View(lstProduct);
        }
    }
}

ShopBanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="~/Content/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="~/Content/admin/dist/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Scripts/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <!-- Font awesome 5 -->
    <link href="fonts/css/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">
    <link href="~/Content/admin/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css" />
    <!-- custom javascript -->
    <script src="~/Content/admin/dist/js/script.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="@Url.Action("Index", "Home")" class="brand-wrap">
                            <img class="logo" style="width:180px;height:400px " src="~/Content/images/coollogo_com-22943684.png">
                        </a>
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form name="search-header">
                            <div class="input-group w-100">
                                <input placeholder="Tìm kiếm" type="text" name="key" class="form-control" />
                                <div class="input-group-append">
                                    <input type="submit" style="background-color:darkorange" name="submit" value="Tìm kiếm" class="form-control" />
                                </div>
                            </div>
                        </form>
                        @*<form name="search-header">
                                <div class="input-group w-100">
                                    <input type="text" class="form-control" placeholder="Nhập từ khóa">

                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit" name="submit">
                                            <i class="fa fa-search"> >Tìm kiếm </a></i>
                                        </button>
                                    </div>
                                </div>
                            </form>*@
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">

                            @if (Session["idUser"] != null)
                            {
                                if (Session["Admin"].Equals(true))
                                {

                                    <div class="widget-header mr-3">
                                        <a href="~/Admin/Product" class="widget-view">
                                            <div class="icon-area">
                                                <i class="fa fa-unlock-alt"></i>
                                            </div>
                                            <a style=" margin-bottom:8px;font-size:12px;" class="text">Quản trị viên</a>
                                        </a>
                                    </div>
                                    <div class="widget-header mr-3">
                                        <a href="~/Home/Logout" class="widget-view">
                                            <div class="icon-area">
                                                <i class="fa fa-sign-in-alt"></i>
                                            </div>
                                            <a style=" margin-bottom:8px;font-size:12px;" class="text">Đăng xuất</a>
                                        </a>
                                    </div>
                                }

                                else
                                {
                                    <div class="widget-header mr-3">
                                        <a href="~/Home/Logout" class="widget-view">
                                            <div class="icon-area">
                                                <i class="fa fa-sign-in-alt"></i>
                                            </div>
                                            <a style=" margin-bottom:8px;font-size:12px;" class="text">Đăng xuất</a>
                                        </a>
                                    </div>
                                }
                            }
                            else
                            {
                                <div class="widget-header mr-3">
                                    <a href="@Url.Action("Login", "Home")" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-user"></i>
                                        </div>
                                        <a class="text" style="margin-bottom: 8px; margin-right: 0px; font-size: 12px;" href="~/Home/Login">Đăng nhập</a>
                                    </a>
                                </div>
                                <div class="widget-header mr-3">
                                    <a href="@Url.Action("Register", "Home")" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-registered"></i>
                                        </div>
                                        <a style=" margin-bottom:8px;font-size:12px;" class="text">Đăng ký</a>
                                    </a>
                                </div>
                            }


                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-store">

                                        </i>
                                    </div>
                                    <small class="text"> Đặt hàng </small>
                                </a>
                            </div>
                            <div class="widget-header">
                                <a href="@Url.Action("Index", "Cart")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-shopping-cart"></i>
                                        <span class="notify" id="CartCount">@Session["count"]</span>
                                    </div>
                                    <small class="text"> Giỏ hàng </small>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="@Url.Action("Index", "Category")"> <i class="fa fa-bars text-muted mr-2"></i> Danh mục </a>
                            <div class="dropdown-menu">
                            
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Khuyến mãi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Search","Home")">Tìm kiếm nhanh</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.facebook.com/pham.vanquang.96742/">Liên hệ</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav ml-md-auto">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">Việt Nam</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">Tiếng Anh</a>
                                <a class="dropdown-item" href="#">Nhật Bản</a>
                                <a class="dropdown-item" href="#">Trung Quốc</a>

                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()
    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Thương hiệu</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Iphone</a></li>
                            <li> <a href="#">Thinkpad</a></li>
                            <li> <a href="#">SamSung</a></li>
                            <li> <a href="#">Xiomi</a></li>
                        </ul>
                    </aside>

                    <aside class="col-md col-6">
                        <h6 class="title">Tài Khoản</h6>
                        <ul class="list-unstyled">
                            <li> <a href="@Url.Action("Login", "Home")"> Đăng nhập </a></li>
                            <li> <a href="@Url.Action("Register", "Home")"> Đăng ký </a></li>
                            <li> <a href="@Url.Action("Index", "Cart")"> Đơn hàng </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Liên hệ</h6>
                        <ul class="list-unstyled">
                            <li><a href="https://www.facebook.com/pham.vanquang.96742"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="https://www.instagram.com/pham.vanquang.96742/"> <i class="fab fa-instagram"></i> Instagram </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Thông tin liên quan</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#"> khuyến mãi </a></li>
                            <li> <a href="#"> Giảm giá </a></li>
                            <li> <a href="@Url.Action("PaymentWithPaypal","Cart")"> Hình thức thanh toán </a></li>
                        </ul>
                    </aside>
                </div>
            </section>

            <section class="footer-bottom text-center">
                <p class="text-muted"> 6, Trần Văn Ơn, P. Phú Hòa, Thành phố Thủ Dầu Một, T. Bình Dương </p>
                <br>
            </section>
        </div>
       
    </footer>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>

</body>
</html>